# Generated by Django 6.0.1 on 2026-03-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_scope_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
