# Generated by Django 6.0.1 on 2026-03-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['tag']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
